dist: trusty

sudo: required

language: minimal

matrix:
  include:
    - env: GO_VERSION=1.12
    - env: GO_VERSION=1.13
    - env: GO_VERSION=$(gimme --known | sort -V | tail -1)

before_install:
  eval "$(gimme ${GO_VERSION})"

script:
  - export GO111MODULE=on
  - go get -t -v $(go list ./... | grep -v examples)
  - ./.travis.gofmt.sh
  - ./.travis.govet.sh
  - go get github.com/mattn/goveralls
  - go test -v -race $(go list ./... | grep -v examples)
  - $GOPATH/bin/goveralls -service=travis-ci -package=$(go list ./... | grep -v examples)